---
"MODEL SEÇME ve DEĞERLENDİRME (CHOOSING AND EVALUATING MODELS)" by Tirendaz Akademi
---

```{r}
data<-read.table("spamD.tsv",header=T, sep="\t")
dim(data)
```
```{r}
data_train<-subset(data,data$rgroup>=10)
data_test<-subset(data,data$rgroup<10)
y<-setdiff(colnames(data), list("rgroup","spam"))
f<-as.formula(paste('spam=="spam"', paste(y,collapse = "+"), sep='~'))
f
```

```{r}
model<-glm(f,family = binomial(link="logit"), data=data)
data_train$pred<-predict(model, newdata = data_train, type="response")
data_test$pred<-predict(model, newdata = data_test, type="response")
```

```{r}
s<-data_test[c(50,100,150,200,250),c("spam","pred")]
s
```
```{r}
cm<-table(truth=data_test$spam, prediction=ifelse(data_test$pred>0.5,"spam","non-spam"))
cm
```
```{r}
(cm[1,1]+cm[2,2])/sum(cm)
```
```{r}
cm[2,2]/(cm[2,2]+cm[1,2])
```
```{r}
cm[2,2]/(cm[2,2]+cm[2,1])
```
```{r}
p<-cm[2,2]/(cm[2,2]+cm[1,2])
r<-cm[2,2]/(cm[2,2]+cm[2,1])
F1<-2*p*r/(p+r)
F1
```
```{r}
data1<-read.csv("crickets.csv")
head(data1)
```
```{r}
model1<-lm(temperatureF~chirp_rate, data=data1)
```

```{r}
data1$t_pred<-predict(model1,newdata = data1)
head(data1)
```

```{r}
e<-(data1$t_pred-data1$temperatureF)^2
(RMSE<-sqrt(mean(e)))
```
```{r}
e2<-(data1$t_pred-data1$temperatureF)^2
v1<-sum(e2)
d2<-(mean(data1$temperatureF)-data1$temperatureF)^2
v2<-sum(d2)
R2<-1-(v1/v2)
R2
```
```{r}
library(WVPlots)
DoubleDensityPlot(data_test,
                  xvar="pred",
                  truthVar = "spam",
                  title = "Skorların Dağılımı")
```

```{r}
ROCPlot(data_test,
        xvar="pred",
        truthVar = "spam",
        truthTarget = "spam",
        title = "Spam Filtresinin Performansı")
```

```{r}
library(sigr)
calcAUC(data_test$pred, data_test$spam=="spam")
```

























































































































