---
"LİNEER REGRESYON (LINEAR REGRESSION)" by Tirendaz Akademi
---
```{r}
data<-readRDS("psub.RDS")
dim(data)
```

```{r}
set.seed(1234)
gp<-runif(nrow(data))
train_data<-subset(data, gp>=0.5)
test_data<-subset(data,gp<0.5)
dim(train_data)
dim(test_data)
```

```{r}
model<-lm(
  log10(PINCP)~AGEP+SEX+COW+SCHL, 
  data=train_data
)
```

```{r}
test_data$pred<-predict(model, newdata = test_data)
train_data$pred<-predict(model, newdata = train_data)
```

```{r}
library("ggplot2")
ggplot(data=test_data, aes(x=pred, y=log10(PINCP)))+
  geom_point(alpha=0.2, color="darkgray")+
  geom_smooth(color="darkblue")+
  geom_line(aes(x=log10(PINCP), y=log10(PINCP)), color="red", linetype=2)+
  coord_cartesian(xlim=c(4,5.25), ylim=c(3.5,5.5))
```

```{r}
r2<-function(y,f){
  1-sum((y-f)^2)/sum((y-mean(y))^2)
}
(r2(log10(train_data$PINCP), train_data$pred))
(r2(log10(test_data$PINCP), test_data$pred))
```

```{r}
coefficients(model)
```

```{r}
levels(data$SCHL)
```

```{r}
10^(0.35-0.10)
```

```{r}
summary(model)
```

```{r}
(resids_test<-summary(
  log10(test_data$PINCP)-predict(model, newdata = test_data)))
```

```{r}
summary(model)$coefficients
```





















































































































