---
"Lojistik Regresyon (Logistic Regression)" - "Tirendaz Akademi"
---

```{r}
load("NatalRiskData.rData")
dim(sdata)
```
```{r}
head(sdata)
```
```{r}
str(sdata)
```
```{r}
set.seed(1234)
train<-sdata[sdata$ORIGRANDGROUP<=5,]
test<-sdata[sdata$ORIGRANDGROUP>5,]
dim(train)
dim(test)
```
```{r}
y<-"atRisk"
x<-c("PWGT","UPREVIS","CIG_REC","GESTREC3","DPLURAL","ULD_MECO","ULD_PRECIP" ,"ULD_BREECH","URF_DIAB","URF_CHYPER","URF_PHYPER","URF_ECLAM","DBWT","ORIGRANDGROUP")
library("wrapr")
f<-mk_formula(y,x)
f
```

```{r}
colnames(sdata)
```
```{r}
model<-glm(f,data=train,family = binomial(link="logit"))
```

```{r}
train$pred<-predict(model,newdata = train, type="response")
test$pred<-predict(model,newdata = test, type="response")
```

```{r}
library("WVPlots")
DoubleDensityPlot(train,"pred","atRisk",title = "Yenidoğanların skorları")
```
```{r}
plt<-PRTPlot(train,"pred","atRisk",TRUE,
             plotvars = c("enrichment","recall"),
             thresholdrange = c(0,0.05),
             title = "Zengileştirme | Duyarlılık")
library("ggplot2")
plt+geom_vline(xintercept = 0.02, color="red", linetype=2)
```
```{r}
cm<-table(pred=test$pred>0.02, atRisk=test$atRisk)
cm
```
```{r}
(p<-cm[2,2]/sum(cm[2,]))
(r<-cm[2,2]/sum(cm[,2]))
(e<-p/mean(as.numeric(test$atRisk)))
```
```{r}
coefficients(model)
```
```{r}
summary(model)
```
```{r}
loglikelihood<-function(y,py){
  sum(y*log(py)+(1-y)*log(1-py))
}
(pnull<-mean(as.numeric(train$atRisk)))
(null.dev<--2*loglikelihood(as.numeric(train$atRisk),pnull))
```
```{r}
model$null.deviance
```
```{r}
(resid.dev<--2*loglikelihood(as.numeric(train$atRisk),train$pred))
```
```{r}
model$deviance
```
```{r}
testy<-as.numeric(test$atRisk)
pnull.test<-mean(testy)
(null.dev.test<--2*loglikelihood(testy,pnull.test))
(resid.dev.test<--2*loglikelihood(testy,test$pred))
```
```{r}
(pr2<-1-(resid.dev/null.dev))
(pr2.test<-1-(resid.dev.test/null.dev.test))
```
```{r}
df.null<-dim(train)[[1]]-1
df.model<-dim(train)[[1]]-length(model$coefficients)
delDev<-null.dev-resid.dev
deldf<-df.null-df.model
p<-pchisq(delDev,deldf,lower.tail = FALSE)
p
```


















































































































